version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      custom_network:
        ipv4_address: 172.21.0.3

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.21.0.2:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      custom_network:
        ipv4_address: 172.21.0.2

  # kafka1:
  #   image: bitnami/kafka:latest
  #   ports:
  #     - "9093:9093"
  #   environment:
  #     - KAFKA_BROKER_ID=2
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.21.0.5:9093
  #     - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   networks:
  #     custom_network:
  #       ipv4_address: 172.21.0.5

  # kafka2:
  #   image: bitnami/kafka:latest
  #   ports:
  #     - "9094:9094"
  #   environment:
  #     - KAFKA_BROKER_ID=3
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://172.21.0.6:9094
  #     - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9094
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   networks:
  #     custom_network:
  #       ipv4_address: 172.21.0.6
  # 3.3.3
  couchdb:
    image: couchdb:latest
    ports:
      - "5990:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      custom_network:
        ipv4_address: 172.21.0.4

volumes:
  couchdb_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
